#version 450

#include "lighting.glsl"
#include "utils.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, rgba8) readonly uniform imageCubeArray gbuffer_color;
layout(binding = 1, rgba8) readonly uniform imageCubeArray gbuffer_normal;
layout(binding = 2, rgba16f) readonly uniform imageCubeArray gbuffer_position;
layout(binding = 3, rgba16f) writeonly uniform imageCubeArray out_radiance;

layout(binding = 4) uniform samplerCube in_envmap;
layout(binding = 5) uniform sampler2D brdf_lut;

layout(binding = 0) uniform Data
{
    FrameData frame;
};

layout(binding = 1) buffer PointLights
{
    PointLight point_lights[];
};

uniform vec3 probe_position;
uniform int base_layer;

void main()
{
    ivec3 size = imageSize(gbuffer_color);
    ivec2 texel = ivec2(gl_GlobalInvocationID.xy);
    if (texel.x >= size.x || texel.y >= size.y)
    {
        return;
    }

    const int layer = base_layer + int(gl_GlobalInvocationID.z);

    const vec4 color = imageLoad(gbuffer_color, ivec3(texel, layer));
    const vec4 normal_data = imageLoad(gbuffer_normal, ivec3(texel, layer));
    const vec4 pos_data = imageLoad(gbuffer_position, ivec3(texel, layer));

    const vec3 base_color = color.rgb;
    const float roughness = color.a;
    const vec3 normal = normalize(normal_data.xyz * 2.0 - 1.0);
    const float metallic = normal_data.w;
    const vec3 world_pos = pos_data.xyz;

    const vec3 view_dir = normalize(probe_position - world_pos);

    vec3 acc = eval_ibl(in_envmap, brdf_lut, normal, view_dir, base_color,
                        metallic, roughness)
        * frame.ibl_intensity;
    acc += frame.sun_color
        * eval_brdf(normal, view_dir, frame.sun_dir, base_color, metallic,
                    roughness);

    for (uint i = 0; i != frame.point_light_count; ++i)
    {
        PointLight light = point_lights[i];
        const vec3 to_light = (light.position - world_pos);
        const float dist = length(to_light);
        const vec3 light_vec = to_light / max(dist, 0.0001);

        const float att = attenuation(dist, light.radius);
        if (att <= 0.0f)
        {
            continue;
        }

        acc += eval_brdf(normal, view_dir, light_vec, base_color, metallic,
                         roughness)
            * att * light.color;
    }

    imageStore(out_radiance, ivec3(texel, layer), vec4(acc, 1.0));
}
